version: "3.4"

services:

  db:
    image: mysql:5.7
    container_name: $AZ_DATABASE_HOST
    environment:
      - MYSQL_ROOT_PASSWORD=$AZ_DATABASE_PASSWORD
      - MYSQL_USER=$AZ_DATABASE_USERNAME
    ports:
      - 3306:3306
    restart: always

  server:
    build: cloud-server
    image: app/cloud-server
    ports: 
      - 80:8080
    depends_on:
      - db
    restart: always
    environment:
      spring.datasource.url: jdbc:mysql://$AZ_DATABASE_HOST:3306/shop?createDatabaseIfNotExist=true
      spring.datasource.username: $AZ_DATABASE_USERNAME
      spring.datasource.password: $AZ_DATABASE_PASSWORD