version: "3.4"

services:

  db-server:
    image: mysql:5.7
    container_name: db-server-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    ports:
      - 3305:3306
    restart: always
    networks:
      - backend

  server:
    build: cloud-server
    image: app/cloud-server
    ports: 
      - 80:8080
    depends_on:
      - db-server
    restart: always
    environment:
      spring.datasource.url: jdbc:mysql://db-server-mysql:3306/shop?createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: root
    networks:
      - backend
  
  client-machine:
    build: machine-to-machine-client
    image: app/machine-to-machine-client
    environment:
      cloud-server.base-url: http://host.docker.internal/
    ports:
      - 81:8081
    networks:
      - backend

networks:
  backend:
    driver: "bridge"