version: "3.4"

services:

  db:
    image: mysql:5.7
    container_name: $ServerName
    environment:
      - MYSQL_ROOT_PASSWORD=$SqlPassword
      - MYSQL_USER=$SqlUserName
    ports:
      - 3306:3306
    restart: always

  server:
    build: cloud-server
    image: app/cloud-server
    ports: 
      - 80:8080
    depends_on:
      - db
    restart: always
    environment:
      spring.datasource.url: jdbc:mysql://$ServerName:3306/testDb?createDatabaseIfNotExist=true&useSSL=true&requireSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
      spring.datasource.username: $SqlUserName
      spring.datasource.password: $SqlPassword