version: "3.4"

services:
  server:
    build: cloud-server
    image: app/cloud-server
    ports: 
      - 80:8080
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${ServerName}:3306/testDb?createDatabaseIfNotExist=true&useSSL=true&requireSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${SqlUserName}
      SPRING_DATASOURCE_PASSWORD: ${SqlPassword}